In [12]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder , StandardScaler

#Pull the dataset straight into a DataFrame

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

#drop columns that are unique identifiers 
df = df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])
#display the first 5 rows and see the type of data I'm dealing with
print(df.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
#separate the numerical and categorical columns
num_cols = ["Age", "Fare"]
cat_cols = ["Sex", "Embarked"]

#inpute the numerical missing values with the median, since median is less sensitive to skewness and outliers in data
for col in num_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())

# input categorical missing values with the mode
for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])
print(df.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [14]:
#drop first column to reduce redundancy and prevent multicollinearity
encoder = OneHotEncoder(sparse_output=False, drop="first")
#fit and transform the categorical text columns
encoded_features = encoder.fit_transform(df[cat_cols])
#convert back to a clean DataFrame with proper column names 
encoded_df = pd.DataFrame(
    encoded_features,
    columns=encoder.get_feature_names_out(cat_cols)
)
#separate our target column("Survived") from our features (X) 
y = df["Survived"]
X = df.drop(columns=["Survived"] + cat_cols)
#concatenate the numerical features with our newly encoded features
X = pd.concat([X.reset_index(drop=True), encoded_df], axis=1)
X.head()

   Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  22.0      1      0   7.2500       1.0         0.0         1.0
1       1  38.0      1      0  71.2833       0.0         0.0         0.0
2       3  26.0      0      0   7.9250       0.0         0.0         1.0
3       1  35.0      1      0  53.1000       0.0         0.0         1.0
4       3  35.0      0      0   8.0500       1.0         0.0         1.0

In [16]:
#split the dataset into a train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")

Training features shape: (712, 8)
Testing features shape: (179, 8)

In [10]:
#Initialise StandardScaler
scaler = StandardScaler()
scale_target_cols = ["Age", "Fare"]

#FIT AND TRANSFORM THE TRAINING DATASET
X_train[scale_target_cols] = scaler.fit_transform(X_train[scale_target_cols])
#ONLY TRANSFORM THE TESTING SET
X_test[scale_target_cols] = scaler.transform(X_test[scale_target_cols])
print("--- Pipeline Complete & Verified ---")
X_train.head()

--- Pipeline Complete & Verified ---

,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
331,1,1.253641,0,0,-0.078684,1.0,0.0,1.0
733,2,-0.477284,0,0,-0.377145,1.0,0.0,1.0
382,3,0.215086,0,0,-0.474867,1.0,0.0,1.0
704,3,-0.246494,1,0,-0.476230,1.0,0.0,1.0
813,3,-1.785093,4,2,-0.025249,0.0,0.0,1.0